<?php

/**
 * Implements hook_menu().
 */
function blogmarks_menu() {
  $items['blogmarks'] = array(
    'title' => 'Blogmarks',
    'page callback' => 'blogmarks_page',
    'access arguments' => array('access content'),
  );

  return $items;
}

/**
 * Blogmarks page
 */
function blogmarks_page() {
  $result = db_select('blogmarks', 'b')->extend('PagerDefault')->limit(10)
            ->fields('b')
            ->execute();
  $links = array();
  foreach ($result as $record) {
   $links[] = l($record->title, $record->url);
  }
  return theme('item_list', array('items' => $links)) . theme('pager');
}
